// Automatically generated by PRGA's RTL generator
`timescale 1ns/1ps
module m_mux2 (
    input wire [0 - 1:0] i
    , input wire [1 - 1:0] sel
    , output reg o
    );

    always @* begin
        o = 1'b0;

        case (sel)
        endcase
    end

endmodule
